### ISSUE TITLE
Add Compatibility without Rails / ActiveSupport

### ISSUE THREAD

**Issue by ttilberg** [connorshea/vscode-ruby-test-adapter#16]
### Your environment

- `vscode-ruby-test-adapter` version:  0.5.4
- Ruby version: 2.5.3
- VS Code version: 1.34.0
- Operating System: Ubuntu

The Ruby in this extension assumes Rails / ActiveSupport is also in play. Here are the changes I had to address to get the extension to work without Rails

- Constant Autoloading (needs `require 'minitest'`, not sure how RSpec is handled)
- ActiveSupport Extensions:
  - `Hash#as_json`
    - Seems to be unnecessary, as JSON.pretty_generate handles this.
  - `String#Constantize`
  - `Hash#deep_dup`
  - `String#starts_with` (similar enough to `#start_with`)

I was documenting how each of these came up, but it became long and noisy. I think it would be easier to just submit a PR and seek your thoughts.

Thanks!

**Comment by connorshea** [comment]
Ah, yeah that wasn’t intentional. RSpec should work fine without Rails, but I didn’t test a Minitest suite without Rails. If you want to open a PR to fix that I’d be happy to merge it :)

**Comment by connorshea** [comment]
Fixed by #17
