### ISSUE TITLE
Workspace shows tests twice

### ISSUE THREAD

**Issue by CalvinWalzel** [connorshea/vscode-ruby-test-adapter#18]
### Your environment

- `vscode-ruby-test-adapter` version: 0.5.5
- Ruby version: 2.6.3
- VS Code version: 1.35.1
- Operating System: macOS 10.14.4
- RSpec version: 3.8 (see below)
```
RSpec 3.8
  - rspec-core 3.8.0
  - rspec-expectations 3.8.3
  - rspec-mocks 3.8.0
  - rspec-rails 4.0.0.beta2
  - rspec-support 3.8.0
```

### Expected behavior
Ruby Test Explorer shows tests once when in a workspace.

### Actual behavior
Ruby Test Explorer shows tests twice when in a workspace [1]. The workspace contains two projects: A rails 6 API only application & a VueJS app. When I open the API folder directly without the workspace, the test suite is shown correctly [2].

Both tests suites shown in [1] work correctly and execute the same command.
The content of the workspace file:
```
{
  "folders": [
    {
      "path": "api"
    },
    {
      "path": "web"
    }
  ],
  "settings": {
    "solargraph.useBundler": true,
    "solargraph.diagnostics": true
  }
}
```

I tried to provide as much information as possible :)

### Screenshots
[1] (Workspace)
<img width="487" alt="image" src="https://user-images.githubusercontent.com/6446452/59568164-61555100-9077-11e9-92f2-9ba1de29c506.png">

[2](Project opened by folder `/api`)
<img width="356" alt="image" src="https://user-images.githubusercontent.com/6446452/59568199-b8f3bc80-9077-11e9-9e0f-9c63e44b5aff.png">

**Comment by connorshea** [comment]
Could you show what the directory structure looks like? (You can get the `tree` command from Homebrew for this)

**Comment by connorshea** [comment]
I ended up happening to reproduce this while working on something else, by just opening multiple workspaces at once. I hadn't really built the extension with multi-root workspace support in mind, but it's now supported with 0.6.0 👍
