### ISSUE TITLE
Returned JSON does not contain nested tests result.

### ISSUE THREAD

**Issue by antondalgren** [connorshea/vscode-ruby-test-adapter#40]
### Your environment

- `vscode-ruby-test-adapter` version: 0.6.1
- Ruby version: 2.6.5
- VS Code version: 1.41
- Operating System: OSX
- Minitest version: 5.11.3

### Expected behavior
Expect the returning JSON to contain results from all tests, including nested tests. 
```
describe ClassToTest do
  describe 'method' do
    it 'returns JSON as expected' do
   
    end
    describe 'another context in method' do
      it 'returns JSON as expected' do

      end
    end
  end
end
```
### Actual behavior

```
describe ClassToTest do
  describe 'method' do
    it 'returns JSON as expected' do
   
    end
    describe 'another context in method' do
      it 'Test runs successfully but does not report the results to JSON' do

      end
    end
  end
end
```

**Comment by connorshea** [comment]
This should be fixed in 0.7.0 thanks to #37, please reopen it if it's not.
