### ISSUE TITLE
`vscode:minitest:list` -> TypeError: no implicit conversion of nil into Integer

### ISSUE THREAD

**Issue by nadnoslen** [connorshea/vscode-ruby-test-adapter#99]
### Your environment

- `vscode-ruby-test-adapter` version: v0.9.0
- Ruby version: 2.7.6p219
- VS Code version: 1.69.1
- Operating System: macOS Monterey 12.4
- RSpec or Minitest version: Minitest 5.16.2

### Expected behaviour

Typically a few seconds pass and my tests load. When they don't it is usually because I have a `rake` error...e.g. my postgres container isn't running the app's database. At this point I'd start the database and perform a VS Code `Developer: Reload Window`. 

### Actual behaviour

In my case, I have two separate Rails applications who are suddenly failing to list tests even when everything seems to be working. I do have some _rake_ noise where some Ruby/Rails trace/deprecation messages are appearing but they are in no way producing a non-zero error code preventing the `vscode:minitest:list` command from succeeding.

Here are the log messages from the extension; note the **no implicit conversion of nil into Integer** ... I'm seeing this in multiple projects.

```
[2022-07-12 20:24:25.727] [INFO] Getting a list of Minitest tests in suite with the following command: DISABLE_SPRING=1 PARALLEL_WORKERS=1 ./bin/rake -R $EXT_DIR vscode:minitest:list
[2022-07-12 20:24:25.727] [INFO] Initialization finished
[2022-07-12 20:24:30.287] [ERROR] Error while finding Minitest test suite: Command failed: DISABLE_SPRING=1 PARALLEL_WORKERS=1 ./bin/rake -R $EXT_DIR vscode:minitest:list
... (I have some deprecation messages from rails here BUT nothing generating an error code) ... 
rake aborted!
TypeError: no implicit conversion of nil into Integer
/Users/.../.vscode/extensions/connorshea.vscode-ruby-test-adapter-0.9.0/ruby/vscode/minitest/tests.rb:33:in `block in build_list'
/Users/.../.vscode/extensions/connorshea.vscode-ruby-test-adapter-0.9.0/ruby/vscode/minitest/tests.rb:32:in `map'
/Users/.../.vscode/extensions/connorshea.vscode-ruby-test-adapter-0.9.0/ruby/vscode/minitest/tests.rb:32:in `build_list'
/Users/.../.vscode/extensions/connorshea.vscode-ruby-test-adapter-0.9.0/ruby/vscode/minitest/tests.rb:9:in `all'
/Users/.../.vscode/extensions/connorshea.vscode-ruby-test-adapter-0.9.0/ruby/vscode/minitest.rb:25:in `list'
/Users/.../.vscode/extensions/connorshea.vscode-ruby-test-adapter-0.9.0/ruby/vscode.rake:8:in `block (3 levels) in <main>'
Tasks: TOP => vscode:minitest:list
(See full trace by running task with --trace)
```

**Comment by SergeyBurtsev** [comment]
The problem is that vscode:minitest:list tries to get list of defined tests calling [Minitest::Test.runnable_methods](https://github.com/connorshea/vscode-ruby-test-adapter/blob/73d58cb091028e100ac6bd9ddf038c79ccf8e944/ruby/vscode/minitest/tests.rb#L33), which depends on seed for [random shuffling](https://github.com/minitest/minitest/blob/6bd249b73c66e6de5fc4d1de5d6a8f383f6644d2/lib/minitest/test.rb#L70). If seed is nil srand throws an exception. Usually Minitest sets seed when CLI options parsed, but that step is skipped here.

My simple workaround is to ensure that seed is set in test_helper.rb

`Minitest.seed ||= 0`

**Comment by connorshea** [comment]
Released a new version of the extension with this fix, thanks :)
